# Generated by Django 6.0.4 on 2026-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.CharField(blank=True, choices=[('CHILDREN', '6-10 years (أطفال)'), ('TWEENS', '11-12 years (البراعم الناضجة)'), ('TEENS', '13-20 years (البالغون)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exact_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TECH_SUPPORT', 'Technical Support'), ('SUPERVISOR', 'Supervisor'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('GUEST', 'Guest')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
