# Generated by Django 6.0.4 on 2026-04-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_parent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
