# Generated by Django 6.0.4 on 2026-06-01 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
