# Generated by Django 6.0.4 on 2026-06-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_session_version'),
        ('chat', '0003_remove_chatroom_study_group_chatroom_course_group'),
        ('learning', '0015_remove_course_target_age_course_target_age_max_and_more'),
        ('live', '0002_virtualsession_sessionfeedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='study_groups',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course_groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='learning.coursegroup'),
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
    ]
