# Generated by Django 6.0.4 on 2026-06-06 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_week_unique_together_remove_week_course_and_more'),
        ('quizzes', '0002_studentresult_attempt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='week',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_quizzes', to='learning.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_quizzes', to='learning.unit'),
        ),
    ]
