# Generated by Django 6.0.4 on 2026-04-24 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('learning', '0003_studentmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='age_group',
            field=models.CharField(blank=True, choices=[('CHILDREN', '6-10 years (أطفال)'), ('TWEENS', '11-12 years (البراعم الناضجة)'), ('TEENS', '13-20 years (البالغون)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='learning.course'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('COMPLAINT', 'Complaint / Tech Support'), ('HOMEWORK', '1-on-1 Homework'), ('COMMUNITY', 'Global Community Forum'), ('TEACHER_FORUM', 'Teachers-Only Forum'), ('AGE_GROUP', 'Age-Group Room'), ('COURSE', 'Course-Specific Room'), ('PRIVATE', 'Private 1-on-1 Chat')], max_length=20),
        ),
    ]
