# Generated by Django 6.0.4 on 2026-06-15 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_age_group_chatroom_course_and_more'),
        ('learning', '0015_remove_course_target_age_course_target_age_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='study_group',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='course_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.coursegroup'),
        ),
    ]
