# Generated by Django 6.0.4 on 2026-06-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_studentaiinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaiinsight',
            name='data_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
