# Generated by Django 6.0.4 on 2026-06-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_studentaiinsight_data_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAIInsight',
        ),
    ]
