# Generated by Django 6.0.4 on 2026-06-06 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_delete_studentaiinsight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='week',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='week',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='course_format',
            field=models.CharField(choices=[('ZOOM_ONLY', 'Zoom Only'), ('VIDEO_ONLY', 'Video Only'), ('HYBRID', 'Hybrid')], default='VIDEO_ONLY', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='course_structure',
            field=models.CharField(choices=[('SHORT_FLAT', 'Short (Flat)'), ('LONG_NESTED', 'Long (Nested)')], default='SHORT_FLAT', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='is_upload_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='target_age',
            field=models.CharField(choices=[('CHILDREN', 'Children'), ('TWEENS', 'Tweens'), ('TEENS', 'Teens'), ('ALL', 'All Ages')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flat_lessons', to='learning.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_attachment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.unit'),
        ),
        migrations.CreateModel(
            name='ZoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_sessions', to='learning.coursegroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='week',
        ),
    ]
