# Generated by Django 6.0.4 on 2026-06-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_week_unique_together_remove_week_course_and_more'),
        ('quizzes', '0003_remove_quiz_week_quiz_course_quiz_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
