# Generated by Django 6.0.4 on 2026-06-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_delete_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, default='أكاديمية نور النبوة', max_length=255, null=True),
        ),
    ]
