# Generated by Django 6.0.4 on 2026-06-15 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_globalsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='target_age',
        ),
        migrations.AddField(
            model_name='course',
            name='target_age_max',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='course',
            name='target_age_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='capacity',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='official_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='official_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='primary_teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
