# Generated by Django 6.0.4 on 2026-07-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_virtualsession_sessionfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualsession',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
